BOARD_TAG   = nano
BOARD_SUB   = atmega328
ARDUINO_DIR = /opt/arduino
MONITOR_PORT = /dev/ttyUSB0

AVRDUDE      = $(ARDUINO_DIR)/hardware/tools/avr/bin/avrdude
AVRDUDE_CONF = $(ARDUINO_DIR)/hardware/tools/avr/etc/avrdude.conf

AVR_TOOLS_PATH = $(ARDUINO_DIR)/hardware/tools/avr/bin
ARDUINO_LIBS = SerialDXL Encoder PID ros_lib


include /opt/arduino-mk/Arduino.mk